# Generated by Django 4.2.9 on 2024-01-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usr_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usr_data",
            old_name="x_speed",
            new_name="speed_x",
        ),
        migrations.RenameField(
            model_name="usr_data",
            old_name="y_speed",
            new_name="speed_y",
        ),
        migrations.RenameField(
            model_name="usr_data",
            old_name="z_speed",
            new_name="speed_z",
        ),
    ]
