# Generated by Django 4.2.9 on 2024-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr_data", "0002_rename_x_speed_usr_data_speed_x_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usr_data",
            name="device_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
